[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_market = "VotAjwzAEF9ZLNAYEB1ivXt51911EqYGVu9NeaEKRyy"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --file ./tests/vote-market-voting.ts --file ./tests/vote-market-rewards.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://mainnet.helius-rpc.com/?api-key=efa64d65-80ac-4f32-a701-fba4acc33236"

[[test.validator.account]]
address = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
filename = "./test-accounts/gaugemeister.json"

[[test.validator.account]]
address = "3xC4eW6xhW3Gpb4T5sCKFe73ay2K4aUUfxL57XFdguJx"
filename = "./test-accounts/gauge.json"

[[test.validator.account]]
address = "2AtXU77mwCTgEEnpAvz9uFUWBNmt7f4rCCGQVKwQBGpw"
filename = "./test-accounts/epoch-gauge.json"

[[test.validator.account]]
address = "C8CMP5RkRQneDtYruTNWbRXihorfXpYh7JdEXjia1DJL"
filename = "./test-accounts/escrow.json"

[[test.validator.account]]
address = "5mMpr6k2AzWVcAPjoJTgfQfbe9HCHTjTUPJm8TxragF"
filename = "./test-accounts/gauge-voter.json"

[[test.validator.account]]
address = "E3NpYfVxUJbUH375vC6MpZE54NZrqc79hvE4U3pUgvou"
filename = "./test-accounts/gauge-vote.json"

[[test.validator.account]]
address = "FXLMDGpLirbot2DY9JCmeKZtvu1TFaWSszE1Bd1kQAn"
filename = "./test-accounts/escrow-no-vote.json"

[[test.validator.account]]
address = "2VshMQTveehVLKvE6mMtxazzz2geq9DKtMJLTqFf79YN"
filename = "./test-accounts/gauge-voter-no-vote.json"

[[test.validator.account]]
address = "3KQwaioayMgkUkrKsDCkQUS7cKrKkqVFko5EhDqhjZjt"
filename = "./test-accounts/gauge-vote-no-vote.json"

[[test.validator.account]]
address = "8erad8kmNrLJDJPe9UkmTHomrMV3EW48sjGeECyVjbYX"
filename = "./test-accounts/locker.json"

[[test.validator.account]]
address = "8J3ePFUwdqJLWN1YPN4fyueKjtmR8nVG7VYhKXXzAzGp"
filename = "./test-accounts/epoch-gauge-voter.json"

[[test.validator.account]]
address = "HmeFZh5TPAM1iuuX8YPkKaAjy9P5vi4f1otP3hMWYhos"
filename = "./test-accounts/epoch-gauge-vote.json"

[[test.validator.account]]
address = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"
filename = "./gauge_program.json"

[[test.validator.account]]
address = "4RV2XFNPa5egEiMLru8814ZqxhZT8eeqFrTxdqxyTaZm"
filename = "./gauge_program_data.json"

[[test.validator.clone]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"